### ISSUE TITLE
[Feat] 검색뷰 플로우 구현

### ISSUE THREAD

**Issue by SeungWon1125** [SOPT-all/35-COLLABORATION-iOS-KAKAOWEBTOON#36]
## 🛠 Issue

- 검색뷰에서 검색할 경우 FilterTab과 CollectionView가 나오는 플로우를 구현합니다.
- 메인화면에서 검색뷰으로 이동 & 검색뷰에서 에피소드뷰로 이동 플로우는 추후 구현합니다. (각 뷰가 완성되면)

<img width="776" alt="스크린샷 2024-11-23 오후 8 09 34" src="https://github.com/user-attachments/assets/462792e7-cdf2-4fec-994b-4f6431b42316">

## 📝 To-do

- [ ] X 버튼시 dismiss 구현
- [ ] filterTab, CollectionView가 나오도록 구현
- [ ] 검색어 삭제시 filterTab, CollectionView 사라지도록 구현
