### ISSUE TITLE
[Feat] HomeView 추가 작업

### ISSUE THREAD

**Issue by SeungWon1125** [SOPT-all/35-COLLABORATION-iOS-KAKAOWEBTOON#62]
## 🛠 Issue

- HomeView 추가 작업을 진행합니다.

## 📝 To-do

- [x] 요일별 웹툰 nil이미지 처리
- [x] header에 요일 기본 선택 처리
- [x] 신작, 완결 분기처리
- [x] 광고 배너 크기 수정
